spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://61.160.36.225:3306/fhvideo_home?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false
    username: ojiatest
    password: ojia305
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      login-timeout: 22
  data-datasource:
    hikari:
      maximum-pool-size: 28
      max-lifetime: 1666666
      login-timeout: 22
    url: jdbc:mysql://61.160.36.225:3306/fhvideo_data?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false
    username: ojiatest
    password: ojia305
    type: com.zaxxer.hikari.HikariDataSource

